[[ plugins ]]
   package = " @netlify/plugin-lighthouse " 

  # isteğe bağlı, lighthouse raporunu sitenizin altındaki bir yola dağıtın 
  [ plugins . inputs . audits ]
     output_path = " reports/lighthouse.html "
